"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import secrets

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load optional local environment file (never committed).
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in {'1', 'true', 'yes', 'on'}

# SECURITY WARNING: keep the secret key used in production secret!
# The key MUST come from the environment (DJANGO_SECRET_KEY) or a local .env
# file. No fallback secret is committed to the repository, and the process
# refuses to start in production without one so a leaked value can never be
# silently reused. In development a per-machine key is generated and persisted
# to .env so signed sessions survive server restarts.
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if not DEBUG:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY must be set to a strong secret value when DEBUG is disabled.'
        )
    SECRET_KEY = secrets.token_urlsafe(64)
    env_file = BASE_DIR / '.env'
    try:
        if not env_file.exists():
            env_file.write_text(f'DJANGO_SECRET_KEY={SECRET_KEY}\n', encoding='utf-8')
        elif 'DJANGO_SECRET_KEY=' not in env_file.read_text(encoding='utf-8'):
            with env_file.open('a', encoding='utf-8') as fh:
                fh.write(f'\nDJANGO_SECRET_KEY={SECRET_KEY}\n')
    except OSError:
        pass

# Demo accounts and the default development password are accepted only when
# the project is running in demo mode. Production deployments should set
# DEMO_MODE=False; when it is omitted, it follows DEBUG.
demo_mode_setting = os.getenv('DEMO_MODE')
DEMO_MODE = (DEBUG if demo_mode_setting is None else demo_mode_setting.lower() in {'1', 'true', 'yes', 'on'})

ALLOWED_HOSTS = [host.strip() for host in os.getenv('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost,testserver').split(',') if host.strip()]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'channels',
    'django.contrib.staticfiles',

    # Local apps
    'core',
    'dashboard',
    'accreditation',
    'resources',
    'intelligence',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.site_nav',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# SQLite is the zero-setup development default. Production can override with
# DJANGO_DB_ENGINE/DJANGO_DB_NAME/... (e.g. postgresql + a PostgreSQL host).
DATABASES = {
    'default': {
        'ENGINE': os.getenv('DJANGO_DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DJANGO_DB_NAME', BASE_DIR / 'db.sqlite3'),
        'USER': os.getenv('DJANGO_DB_USER', ''),
        'PASSWORD': os.getenv('DJANGO_DB_PASSWORD', ''),
        'HOST': os.getenv('DJANGO_DB_HOST', ''),
        'PORT': os.getenv('DJANGO_DB_PORT', ''),
        'CONN_MAX_AGE': 60,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    # CompressedStaticFilesStorage avoids needing `collectstatic` for dev/tests.
    # For strict production caching, switch to
    # whitenoise.storage.CompressedManifestStaticFilesStorage and run collectstatic.
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Caching
# -----------------
# LocMemCache is the zero-setup default for development. Set
# DJANGO_CACHE_BACKEND=django_redis.cache.RedisCache and
# DJANGO_CACHE_LOCATION=redis://localhost:6379/1 in production for a shared
# cache that also backs sessions via django-redis.
CACHES = {
    'default': {
        'BACKEND': os.getenv('DJANGO_CACHE_BACKEND', 'django.core.cache.backends.locmem.LocMemCache'),
        'LOCATION': os.getenv('DJANGO_CACHE_LOCATION', 'unique-ams-cache'),
    }
}


# Channel layers (WebSockets)
# ---------------------------
# InMemoryChannelLayer is the zero-setup development default and works with no
# external services (and inside the test runner). Set REDIS_URL
# (e.g. redis://redis:6379/1) in production to switch to the Redis-backed
# layer so WebSocket events fan out across multiple processes.
REDIS_URL = os.getenv('REDIS_URL', '')
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': (
            'channels_redis.core.RedisChannelLayer'
            if REDIS_URL else
            'channels.layers.InMemoryChannelLayer'
        ),
        'CONFIG': ({'hosts': [REDIS_URL]} if REDIS_URL else {}),
    }
}


# Security hardening
# ------------------
# On by default in production (DEBUG=False) and off in development. Override
# either way with DJANGO_ENABLE_HTTPS.
ENABLE_HTTPS = os.getenv('DJANGO_ENABLE_HTTPS', str(not DEBUG)).lower() in {'1', 'true', 'yes', 'on'}

SECURE_SSL_REDIRECT = ENABLE_HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = ENABLE_HTTPS
CSRF_COOKIE_SECURE = ENABLE_HTTPS
CSRF_COOKIE_HTTPONLY = True
SECURE_HSTS_SECONDS = 31536000 if ENABLE_HTTPS else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = ENABLE_HTTPS
SECURE_HSTS_PRELOAD = ENABLE_HTTPS
SECURE_REFERRER_POLICY = 'same-origin'

# Rate limiting defaults (per IP, per endpoint).
RATE_LIMIT_LOGIN = {'limit': 5, 'window': 300}
RATE_LIMIT_REGISTER = {'limit': 3, 'window': 3600}
RATE_LIMIT_COMPANION = {'limit': 30, 'window': 300}
RATE_LIMIT_MESSAGES = {'limit': 60, 'window': 300}


# Sessions
# --------
# Session cookies are HttpOnly by default in Django. Keep sessions short-lived
# and bound to the browser in production.
SESSION_COOKIE_AGE = 60 * 60 * 8
SESSION_EXPIRE_AT_BROWSER_CLOSE = not DEBUG


# Upload limits
# -------------
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5 MB (evidence file payloads live on disk, not memory)


# AI / AVA (AI Insights & Assistant) provider
# -------------------------------------------
# When AI_BASE_URL and AI_API_KEY are configured, the intelligence engine calls
# an OpenAI-compatible chat-completions endpoint for generative answers. Without
# them the engine answers deterministically from the live accreditation data,
# so the feature always works.
AI_BASE_URL = os.getenv('AI_BASE_URL', '').rstrip('/')
AI_API_KEY = os.getenv('AI_API_KEY', '')
AI_MODEL = os.getenv('AI_MODEL', 'gpt-4o-mini')
AI_TIMEOUT = int(os.getenv('AI_TIMEOUT', '20'))
AI_MAX_TOKENS = int(os.getenv('AI_MAX_TOKENS', '900'))
AI_ENABLED = bool(AI_BASE_URL and AI_API_KEY)


# Logging
# -------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'filters': ['require_debug_false'],
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        },
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'accreditation': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'accounts': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'intelligence': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'resources': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}
