# Evidence items grouped by sub-area code.
EVIDENCE_ITEMS = {
    "1.1": (
        ("1.1.1", "JMCFI Philosophy, Vision, Mission, and Goals"),
        ("1.1.2", "Articles of Incorporation/SEC Registration"),
        ("1.1.3", "JMCFI Core Values"),
        ("1.1.4", "JMCFI Roadmap"),
        ("1.1.5", "JMCFI Institutional Quality Framework"),
    ),
    "1.2": (
        ("1.2.1", "Department Objectives"),
        ("1.2.2", "Picture of Posted Department Objectives in the Campus"),
    ),
    "1.3": (
        ("1.3.1", "Program Educational Objectives (PEOs)/Student Outcomes (SOs)"),
        ("1.3.2", "Sample Course Outline/Syllabi Showing PEOs and CLOs"),
        ("1.3.3", "Research/Report of Industry Awareness on Programs' PEOs and CLOs"),
        ("1.3.4", "Syllabus with PEOs and CLOs posted in the LMS"),
    ),
    "1.4": (
        ("1.4.1", "Proceedings of Meetings/Programs with Faculty and Staff"),
        ("1.4.2", "Orientation Program of New Employees by HRMD"),
        ("1.4.3", "Sample Syllabi/Course Outline Showing VMG, Core Values, PEOs and CLOs"),
        ("1.4.4", "Received Copy of Promulgated PEOs and CLOs or Syllabi"),
        ("1.4.5", "Program on Freshmen Orientation and Campus Tour"),
        ("1.4.6", "Orientation Program/Attendance Sheets"),
        ("1.4.7", "Awareness and Acceptance of VMG and Core Values by Faculty, Staff and Students"),
        ("1.4.8", "Faculty Loading Contract and Job Description"),
        ("1.4.9", "List of Co-Curricular Activities of Students"),
        ("1.4.10", "Evaluation Reports of Co-Curricular Activities"),
    ),
    "1.5": (
        ("1.5.1", "Awards and Recognitions Received"),
        ("1.5.2", "Exit Survey Results on Realization of PEO"),
        ("1.5.3", "Survey Results on Course Delivery Evaluation"),
        ("1.5.4", "News Clippings on Awards/Recognition Received by the Institution"),
        ("1.5.5", "Quality Management Policy"),
        ("1.5.6", "Work Instructions Manual"),
        ("1.5.7", "Job Description Manual"),
        ("1.5.8", "Employee Manual"),
        ("1.5.9", "Student Handbook"),
        ("1.5.10", "Tracer Study/Graduate Profile"),
    ),
    "2.1": (
        ("2.1.1", "Policy on Employee Hiring, Selection and Placement"),
        ("2.1.2", "Faculty Profile"),
        ("2.1.3", "Credentials of Faculty"),
        ("2.1.4", "Summary List of Faculty Licenses"),
        ("2.1.5", "Summary of Performance Evaluation"),
        ("2.1.6", "Practical Exposure of Faculty, Certifications and Assessments Acquired by the Faculty"),
        ("2.1.7", "Profile and Credentials of Faculty Handling OJT"),
        ("2.1.8", "Summary of Training Seminars Attended by Faculty"),
    ),
    "2.2": (
        ("2.2.1", "Syllabi Showing VMG and Core Values, Program Educational Objectives, Student Learning Outcomes"),
        ("2.2.2", "Sample Tests on VMG and Core Values"),
        ("2.2.3", "Evidences of Faculty Preparedness"),
        ("2.2.4", "Proof of Library Utilization by Faculty"),
        ("2.2.5", "Research Budget SY 2025-2026 and Proposed Budget (2026-2027)"),
        ("2.2.6", "Sample Faculty Research Outputs"),
        ("2.2.7", "Appointment of Research Advisers"),
        ("2.2.8", "List of Faculty Research Productivity (Presentation, Publication and Utilization)"),
        ("2.2.9", "Sample Faculty Research Published in a Journal or Bulletin"),
        ("2.2.10", "Instructional Materials Produced by Faculty"),
        ("2.2.11", "Consultation Schedule"),
        ("2.2.12", "Student Consultation Monitoring Report and Comparative Evaluation Rating of Students Who Have Gone Consultation/Mentoring/Academic Advising"),
    ),
    "2.3": (
        ("2.3.1", "Policy on Faculty Loading, Extra Load and Substitution"),
        ("2.3.2", "Faculty Loading with Course Specialization, Time Schedule"),
        ("2.3.3", "Faculty Loading Contract"),
        ("2.3.4", "Faculty Extra Load and Administrative Assignments"),
        ("2.3.5", "Faculty-Student Ratio"),
    ),
    "2.4": (
        ("2.4.1", "Policy on Academic Ranking and Classification"),
        ("2.4.2", "Faculty Academic Ranking Form"),
        ("2.4.3", "Policy on Employee Performance Evaluation"),
        ("2.4.4", "Performance Evaluation Scales/Questionnaires"),
        ("2.4.5", "Summary of Performance Evaluation"),
        ("2.4.6", "Faculty Salary Scale"),
        ("2.4.7", "Policy on Conditions of Employment"),
        ("2.4.8", "Policy on Employee Leave Benefits"),
        ("2.4.9", "Policy on Employee Fringe Benefits"),
        ("2.4.10", "Policy on Personnel Discipline"),
    ),
    "2.5": (
        ("2.5.1", "Institutional Strategic Plan, 202x-202x"),
        ("2.5.2", "Department Annual Operational Plan of SY 2025-2026 and SY 2026-2027"),
        ("2.5.3", "Policy on Personnel Development"),
        ("2.5.4", "Faculty Development"),
        ("2.5.5", "Faculty Scholarship"),
        ("2.5.6", "Approved Budget for Faculty Development SY 2024-2025 and 2025-2026"),
        ("2.5.7", "Summary of In-House and Offsite Trainings and Seminars"),
        ("2.5.8", "Evaluation of the Faculty Development Plan"),
        ("2.5.9", "Faculty Involvement in Professional Organizations"),
        ("2.5.10", "Policy on Industry Immersion of Faculty"),
    ),
    "2.6": (
        ("2.6.1", "Functional Chart of Research Development and Publication Office (RDPO)"),
        ("2.6.2", "Functional Chart of Social Work Department (CASE)"),
        ("2.6.3", "Job Description of Research Personnel"),
        ("2.6.4", "Research Agenda"),
        ("2.6.5", "Research Budget and Incentives"),
        ("2.6.6", "Operational Procedures of RDPO"),
        ("2.6.7", "List of Research/Project Outputs"),
        ("2.6.8", "List of Faculty Research Productivity (Presentation, Publication and Utilization)"),
    ),
    "2.7": (
        ("2.7.1", "Individual Faculty Member Portfolio"),
        ("2.7.2", "List of Awards/Citations/Recognitions Received by the Faculty"),
        ("2.7.3", "Employee Manual"),
        ("2.7.4", "RDPO Manual"),
        ("2.7.5", "JMS (institutional) and Scholares (student journal) journals"),
    ),
    "3.1": (
        ("3.1.1", "Program Educational Objectives/Student Learning Outcomes"),
        ("3.1.2", "Curriculum"),
        ("3.1.3", "JMCFI Brochure/Program Brochure"),
        ("3.1.4", "Policy on Student OJT/Practicum/Internship"),
        ("3.1.5", "Sample Course Syllabus Showing VMG and Core Values, PEOs, SOs"),
        ("3.1.6", "Policy on Curriculum Review and Validation"),
        ("3.1.7", "Minutes of Meeting on Curriculum Revision"),
        ("3.1.8", "Evidences on OBE Implementation"),
    ),
    "3.2": (
        ("3.2.1", "Policy on Conduct of Student Development Activities"),
        ("3.2.2", "Program/Plan on the Conduct of Co-curricular Activities"),
        ("3.2.3", "Evidences of Co-Curricular Activities"),
        ("3.2.4", "Results of Assessment and Evaluation of Co-curricular Activities"),
        ("3.2.5", "Sample Student Portfolios"),
    ),
    "3.3": (
        ("3.3.1", "Syllabi Compilation"),
        ("3.3.2", "List of Textbooks and References Used"),
        ("3.3.3", "List of Recommended Assessment Tasks"),
        ("3.3.4", "Proof of Use of Learning Management System"),
        ("3.3.5", "Faculty and Student Library Utilization Reports"),
        ("3.3.6", "Evidences of Class Activities and Multimedia Technology Use"),
        ("3.3.7", "Online Student Outputs"),
        ("3.3.8", "Policy on Conduct of Undergraduate Research"),
        ("3.3.9", "List of Students' Research Outputs"),
        ("3.3.10", "Research Activities/Outputs of Students"),
        ("3.3.11", "Policy on Student OJT/Practicum/Internship"),
        ("3.3.12", "On-the-Job Training Manual"),
        ("3.3.13", "List of Host Training Establishments and Industry Partners"),
        ("3.3.14", "Memorandum of Agreement with Industry Partners"),
        ("3.3.15", "On-the-Job Training Evaluation Reports/Portfolio"),
        ("3.3.16", "Sample Student Essays/Reflection Papers"),
    ),
    "3.4": (
        ("3.4.1", "Policy on Classroom Management"),
        ("3.4.2", "Sample Seat Plan"),
        ("3.4.3", "Appointment of Laboratory Custodian"),
        ("3.4.4", "Sample Class List Showing Number of Students"),
        ("3.4.5", "Inventory of Subjects with Number of Students"),
    ),
    "3.5": (
        ("3.5.1", "Policy on Student Assessment"),
        ("3.5.2", "Documents for Class Evaluation"),
        ("3.5.3", "Research/Evaluation Conducted on the Validity and Reliability of Assessment"),
        ("3.5.4", "Analysis and Evaluation Results of Students' Performance"),
        ("3.5.5", "Sample Student Outputs"),
        ("3.5.6", "Sample Class Record"),
        ("3.5.7", "Policy on Student Retention"),
        ("3.5.8", "Policy on Award of Academic Honors"),
        ("3.5.9", "List of Beneficiaries for GOEF"),
        ("3.5.10", "List of Academic Scholars"),
    ),
    "3.6": (
        ("3.6.1", "Policy of Faculty Attendance"),
        ("3.6.2", "Policy on Faculty Loading, Extra Load and Substitution"),
        ("3.6.3", "Sample Dean's Test/Final Exam Approved by Dean/Program Head"),
        ("3.6.4", "Proof of Use of Learning Management System"),
        ("3.6.5", "Compliance Report on Laboratory Equipment/Apparatus as per CHED Requirement"),
        ("3.6.6", "Classroom Visit Plan of Dean"),
        ("3.6.7", "Sample Notices and Minutes of Faculty Meeting"),
        ("3.6.8", "Policy on Student Consultation Services"),
        ("3.6.9", "Consultation Schedule"),
        ("3.6.10", "Student Consultation Appointment Monitoring"),
        ("3.6.11", "Summary on Student Consultation Appointment"),
        ("3.6.12", "Faculty Evaluation Report"),
        ("3.6.13", "Faculty and Staff Development Program"),
        ("3.6.14", "Faculty Awards and Recognition"),
        ("3.6.15", "Recognition Program"),
        ("3.6.16", "Minutes of Meeting of Faculty with Administrative Officials, Students with Administrative Officials"),
        ("3.6.17", "Minutes of Industry Forum"),
        ("3.6.18", "Student Advising Program"),
        ("3.6.19", "Enhancement/Intervention Program"),
    ),
    "3.7": (
        ("3.7.1", "Competition Attended by the Students"),
        ("3.7.2", "Program Advisory Council Membership with Appointment"),
        ("3.7.3", "Course Learning Outcomes (CLO) Attainment Reports"),
        ("3.7.4", "Exit Survey Data Analysis Report"),
        ("3.7.5", "Tracer Study"),
        ("3.7.6", "Correlation of Analysis in the Licensure Examination (if applicable)"),
    ),
    "4.1": (
        ("4.1.1", "List of Laboratory Subjects/Enrolment Schedule"),
        ("4.1.2", "Floor Plans of Laboratory Rooms"),
        ("4.1.3", "Pictures Showing the Following"),
        ("4.1.4", "Fire Safety Certificate"),
        ("4.1.5", "Laboratory Equipment Manual"),
        ("4.1.6", "Networked Computer Laboratory Rooms"),
        ("4.1.7", "Laboratory Development Plan"),
    ),
    "4.2": (
        ("4.2.1", "List of Equipment, Materials and Supplies"),
        ("4.2.2", "Certificate of Ownership for Licensed Computer Software/Courseware"),
    ),
    "4.3": (
        ("4.3.1", "Policy on Use of Computing Laboratories"),
        ("4.3.2", "Policy on Purchasing Process"),
        ("4.3.3", "Copies of Requisition Slips and Proof of Purchases"),
        ("4.3.4", "Policy on Maintenance/Issuance of Laboratory Equipment and Consumable Items"),
        ("4.3.5", "Policy on Preventive Maintenance"),
        ("4.3.6", "Preventive Maintenance Schedule (SY 2026-2027)"),
        ("4.3.7", "Policy on Request for Repair"),
        ("4.3.8", "Profile of Laboratory Custodian/Laboratory Technician"),
        ("4.3.9", "Proof of Utilization of Laboratory Equipment"),
    ),
    "4.4": (
        ("4.4.1", "Policy on Use of Instructional Laboratories"),
        ("4.4.2", "Policy on Laboratory Safety Guidelines"),
    ),
    "4.5": (
        ("4.5.1", "List of Laboratory Manuals"),
        ("4.5.2", "Sample Laboratory Exercises"),
        ("4.5.3", "Evaluation of Skills and Performance of Students"),
        ("4.5.4", "Rubrics Used to Evaluate the Students Performance in the Laboratories"),
        ("4.5.5", "List of Submitted Laboratory Exercises and Experiments"),
        ("4.5.6", "Class Records of Faculty Members Showing the Grades of Students"),
    ),
    "5.1": (
        ("5.1.1", "Research Vision, Mission and Goal"),
        ("5.1.2", "Research Framework"),
        ("5.1.3", "Research Agenda 2026-2030"),
        ("5.1.4", "Policy on Conduct of Institutional Research"),
        ("5.1.5", "Policy on Conduct of Undergraduate Thesis"),
        ("5.1.6", "Conduct of Undergraduate Capstone Project, Business Plan, and Feasibility Study"),
    ),
    "5.2": (
        ("5.2.1", "Research Functional Chart"),
        ("5.2.2", "Job Description of Research Personnel"),
        ("5.2.3", "Profile of Research Personnel"),
        ("5.2.4", "Qualification of Research Mentors"),
        ("5.2.5", "Research Capability Building Program (2025-2026)"),
    ),
    "5.3": (
        ("5.3.1", "Sample Curriculum Showing Research Component (Undergraduate)"),
        ("5.3.2", "Syllabus of Research Subjects"),
        ("5.3.3", "Collaborative/Commissioned Researches"),
        ("5.3.4", "List of Research Linkages"),
        ("5.3.5", "Faculty Research Productivity (Production, Presentation, Publication)"),
        ("5.3.6", "Sample of Faculty Research Output"),
        ("5.3.7", "Sample of Student Research Output"),
    ),
    "5.4": (
        ("5.4.1", "List of Research Books and Instructional Materials"),
        ("5.4.2", "Evaluation Criteria for Approving Institutional Research Proposals"),
        ("5.4.3", "Thesis/Capstone Evaluation Instruments"),
        ("5.4.4", "Sample Minutes of Oral Defense"),
        ("5.4.5", "Catalogued Institutional Researches"),
        ("5.4.6", "Catalogued Student Theses and Capstone Projects"),
    ),
    "5.5": (
        ("5.5.1", "List of Research Incentives"),
        ("5.5.2", "Policy on Research as Criteria for Ranking and Promotion"),
        ("5.5.3", "Policy on Faculty Deloading for Research"),
        ("5.5.4", "Research Budget"),
        ("5.5.5", "Institutional Support/Grant for Student Research"),
        ("5.5.6", "Research Fellowship Program"),
        ("5.5.7", "Research Resources and Software"),
    ),
    "5.6": (
        ("5.6.1", "Policy on Paper Presentation"),
        ("5.6.2", "Policy on Publication of Research Outputs"),
        ("5.6.3", "Public Lectures"),
        ("5.6.4", "List of Paper Presentations/Publications by Students"),
        ("5.6.5", "Student Research Congress"),
        ("5.6.6", "Evaluation Studies for Community Extension Programs"),
        ("5.6.7", "Recognition of Research Utilization"),
        ("5.6.8", "Research Utilization Report"),
    ),
    "5.7": (
        ("5.7.1", "Policy on Research Ethics"),
        ("5.7.2", "Provisions for the Strict Implementation of Documentation Standards and Format"),
        ("5.7.3", "Sample Plagiarism Check Report (DrillBit)"),
        ("5.7.4", "Sample Grammarly Report"),
        ("5.7.5", "Intellectual Property Policy"),
    ),
    "5.8": (
        ("5.8.1", "Accomplishment Reports"),
        ("5.8.2", "Research Awards"),
        ("5.8.3", "Institutional Strategic Plan for Research"),
        ("5.8.4", "Annual Operational Plan for Research"),
        ("5.8.5", "Research Manual"),
        ("5.8.6", "Sample Outputs of Collaborative Research Projects"),
        ("5.8.7", "Research Journals"),
        ("5.8.8", "Proof of Paper Presentations"),
        ("5.8.9", "Proof of Paper Publications"),
    ),
    "6.1": (
        ("6.1.1", "JMCFI Organizational Chart and Library Functional Chart"),
        ("6.1.2", "Educational Qualification and License of Chief Librarian"),
        ("6.1.3", "Appointment Paper and Profile of the Chief Librarian"),
        ("6.1.4", "Job Description of Chief Librarian"),
        ("6.1.5", "Evidence of Chief Librarian's Participation in the Different Committee Meetings"),
        ("6.1.6", "Library Action Committees"),
        ("6.1.7", "Library Processes"),
        ("6.1.8", "Annual Operational Plan"),
        ("6.1.9", "Annual Accomplishment Report / Progress Report"),
    ),
    "6.2": (
        ("6.2.1", "Library Personnel"),
        ("6.2.2", "Staff Development Program for LIC Personnel"),
        ("6.2.4", "Performance Evaluation Reports of Librarians"),
        ("6.2.5", "Staff Compensation, Retirement and Fringe Benefits"),
    ),
    "6.3": (
        ("6.3.1", "Policy on Selection and Acquisition of Print and Non-Print Materials"),
        ("6.3.2", "Collection Development Policy"),
        ("6.3.3", "Participation of the Academic Community in Book Selection"),
        ("6.3.4", "Collection Intensity Level by Discipline"),
        ("6.3.5", "Library Holdings Compliance Report"),
        ("6.3.6", "Professional Books per Program"),
        ("6.3.7", "List of General Education Books"),
        ("6.3.8", "List of Library Holdings Per Section"),
        ("6.3.9", "Preservation and Maintenance of Collection"),
        ("6.3.10", "Tools in Organizing the Library Collections"),
        ("6.3.11", "Evidences that Periodical Collections are recorded and indexed"),
        ("6.3.12", "Evidences that Electronic Resources and AV Materials are Cataloged"),
        ("6.3.13", "Online Public Access Catalog (OPAC)"),
    ),
    "6.4": (
        ("6.4.1", "Information Literacy Program / Library Instruction Program"),
        ("6.4.2", "Library Service Hours"),
        ("6.4.3", "Schedule of Duty of Librarians"),
        ("6.4.4", "Pictures of Open Shelves"),
        ("6.4.5", "Information Dissemination and Promotional Activities"),
        ("6.4.6", "Bulletin Board Display of New Book Acquisitions Public Relations, Promotional and Marketing Services"),
        ("6.4.7", "Enhanced Library Services"),
        ("6.4.8", "Library Consortia/Networks"),
        ("6.4.9", "Library Utilization Statistics/Graphical Presentations - Library Utilization Analysis Report"),
        ("6.4.10", "Library Attendance"),
    ),
    "6.5": (
        ("6.5.1", "Approved Library Budget"),
        ("6.5.2", "Proposed Library Budget (SY 2026-2027)"),
        ("6.5.3", "Budget Performance for the Last Three Years"),
        ("6.5.4", "List of Endowments, Gifts and Exchanges"),
        ("6.5.5", "Minutes of Budget Hearing"),
    ),
    "6.6": (
        ("6.6.1", "Location Site and Floor Plan"),
        ("6.6.2", "Space Requirements"),
        ("6.6.3", "Furniture and Equipment"),
        ("6.6.4", "Physical Provision for Reading Comfort"),
        ("6.6.5", "Security/Control System"),
        ("6.6.6", "Security Control"),
    ),
    "6.7": (
        ("6.7.1", "Specialized Services"),
        ("6.7.2", "Information Literacy Program Evaluation Report"),
        ("6.7.3", "Report Submitted to Management Committee"),
        ("6.7.4", "User Feedback Report"),
        ("6.7.5", "Other evidences"),
    ),
    "7.1": (
        ("7.1.1", "JMCFI Organizational Chart"),
        ("7.1.2", "Functional Chart of Student Support Services (SSS)"),
        ("7.1.3", "Qualification of the Heads of SPS Offices/Functions"),
        ("7.1.4", "SPS Personnel Profile"),
        ("7.1.5", "Monthly Inventory Report of each SPS Offices"),
    ),
    "7.2": (
        ("7.2.1", "JMCFI Vision, Mission and Core Values"),
        ("7.2.2", "Objectives of the Student Support Services"),
        ("7.2.3", "Objectives of SSS Offices"),
        ("7.2.4", "Operational Procedures of the Different SSS Offices"),
        ("7.2.5", "Student Handbook and JMCFI Brochure"),
        ("7.2.6", "Sample Minutes of Meetings Attended by the Different SSS Heads"),
    ),
    "7.3": (
        ("7.3.1", "Framework of Student Support Services"),
        ("7.3.2", "Annual Operational Plan of each SSS Office"),
        ("7.3.3", "Annual Accomplishment Report of each SSS Office"),
        ("7.3.4", "Annual Guidance Plan"),
        ("7.3.5", "Approved Annual Budget"),
        ("7.3.6", "Policy on Standard Conditions and Regulations for the Operation of Concession/s"),
        ("7.3.7", "Profile of Canteen Staff"),
        ("7.3.8", "Permit to Operate Canteen"),
        ("7.3.9", "Health Certificate of Canteen Personnel"),
        ("7.3.10", "Picture of Kitchen and Dining Area of Canteen"),
        ("7.3.11", "Sample Menu"),
        ("7.3.12", "Policy on Bookstore Operations"),
        ("7.3.13", "Profile of Bookstore Staff"),
        ("7.3.14", "Picture of Photocopying Machines"),
        ("7.3.15", "Policy on Transportation Services"),
        ("7.3.16", "List of Vehicles Available for Official Use"),
        ("7.3.17", "Profile of Drivers and their Licenses"),
        ("7.3.18", "Sample Request/s for Vehicle Use Form"),
    ),
    "7.4": (
        ("7.4.1", "Satisfaction/Dissatisfaction Survey for All Student Services"),
        ("7.4.2", "Graduate Exit Survey Reports (GESR) for Student Services"),
        ("7.4.3", "Research on Effectiveness of Student Support Programs"),
        ("7.4.4", "Evaluation of Co/Extra Curricular Activities"),
        ("7.4.5", "Management Review Report on Student Services"),
        ("7.4.6", "Action Plans based on Evaluation Results"),
    ),
    "7.5": (
        ("7.5.1", "Conduct of Freshmen Orientation"),
        ("7.5.2", "Student Handbook"),
        ("7.5.3", "Guidance Services and Testing Center"),
        ("7.5.4", "JMarian Publication"),
        ("7.5.5", "Guidance Manual"),
        ("7.5.6", "Finance Office"),
        ("7.5.7", "Office of Student Affairs"),
        ("7.5.8", "Clinic"),
        ("7.5.9", "Alumni and External Relations"),
        ("7.5.10", "Security Office"),
        ("7.5.11", "Result of Customer Feedbacks"),
        ("7.5.12", "List of Completed and Ongoing SSS Researches"),
        ("7.5.13", "Sample Researches"),
    ),
    "7.6": (
        ("7.6.1", "Objectives of the Internationalizations Office"),
        ("7.6.2", "Functional Chart of the Internationalizations Office"),
        ("7.6.3", "Profile of Internationalizations Office Personnel"),
        ("7.6.4", "Processes of the Internationalizations Office"),
        ("7.6.5", "Proposed Operational Plan for IZN with Alignments"),
        ("7.6.6", "Accomplishment Report"),
        ("7.6.7", "Constitution and By-Laws, Registration Documents, and List of Officers of Alumni Association"),
        ("7.6.8", "Plans and Programs of the Alumni Association"),
        ("7.6.9", "Screenshots of Website of the Alumni Office"),
        ("7.6.10", "Screenshots of Database of Alumni Membership"),
    ),
    "8.1": (
        ("8.1.1", "Profile of Partner Communities"),
        ("8.1.2", "Needs Assessment"),
        ("8.1.3", "Resource Map of Partner Communities"),
        ("8.1.4", "Major Areas of Programming"),
        ("8.1.5", "Memorandum of Agreement (MOA) with Partner Communities"),
    ),
    "8.2": (
        ("8.2.1", "List of Linkages and Accomplishments for the Last Five Years"),
        ("8.2.2", "Objectives: JMCFI Community Extension Services"),
        ("8.2.3", "Community Extension Services Framework"),
        ("8.2.4", "Community Extension Manual"),
        ("8.2.5", "Records/Photos Showing Use of Community/JMCFI Resources"),
        ("8.2.6", "Memorandum of Agreement (MOA) with Partner Institutions"),
    ),
    "8.3": (
        ("8.3.1", "Institutional Strategic Plan SY 2022-2027"),
        ("8.3.2", "Community Extension Services Components"),
        ("8.3.3", "Annual Operational Plan for SY 2024-2025 and SY 2025-2026"),
        ("8.3.4", "Operational Procedures"),
    ),
    "8.4": (
        ("8.4.1", "Year End Accomplishment Report SY 2025-2026"),
        ("8.4.2", "Minutes of Community Consultations"),
        ("8.4.3", "Project Proposal of Banner Project/s"),
        ("8.4.4", "Activity Evaluation Report"),
    ),
    "8.5": (
        ("8.5.1", "Banner Project Portfolios"),
        ("8.5.2", "Extension Activities of Student Organizations"),
        ("8.5.3", "Extension Activities of Non-Teaching Staff"),
        ("8.5.4", "Organizational Chart/CES Functional Chart"),
        ("8.5.5", "Annual Budget"),
        ("8.5.6", "Evaluation Researches/Impact Study"),
    ),
    "9.1": (
        ("9.1.1", "Campus Map"),
        ("9.1.2", "Vicinity Map"),
        ("9.1.3", "Operational Procedures for Security and Safety"),
    ),
    "9.2": (
        ("9.2.1", "Campus Site Plan"),
        ("9.2.2", "Floor Plans of Buildings"),
        ("9.2.3", "Institutional Strategic Plan, 2021-2026"),
        ("9.2.4", "Five-Year Physical Development Plan"),
        ("9.2.5", "Provisions for Traffic Safety"),
        ("9.2.6", "Provisions for Safe Drinking Facilities"),
        ("9.2.7", "No Smoking Area Campus"),
    ),
    "9.3": (
        ("9.3.1", "Certificate of Occupancy"),
        ("9.3.2", "Fire Safety and Inspection Certificate"),
        ("9.3.3", "Picture of Restrooms Provided Separately for Men and Women"),
        ("9.3.4", "Policy on Physical Plant Maintenance"),
        ("9.3.5", "Policy on Ground Maintenance"),
        ("9.3.6", "Preventive Maintenance Checklists"),
        ("9.3.7", "Fire Drill"),
        ("9.3.8", "Pictures of the following"),
        ("9.3.9", "Water Potability Test Result"),
        ("9.3.10", "Evidences for Pest Control"),
        ("9.3.11", "Provision for Tele-Broadcast System"),
        ("9.3.12", "Policy on Janitorial Services"),
        ("9.3.13", "Checklist for Cleaning of Restroom"),
        ("9.3.14", "Inventory of Equipment for Cleaning"),
    ),
    "9.4": (
        ("9.4.1", "Floor Plan of Regular Classroom"),
        ("9.4.2", "Inventory of Classrooms"),
        ("9.4.3", "Certificate of Illumination"),
        ("9.4.4", "Provision for LCD Projectors"),
        ("9.4.5", "Checklist for Cleaning of Room"),
    ),
    "9.5": (
        ("9.5.1", "Floor Plans/Layout of Offices"),
        ("9.5.2", "Monthly Property Inventory/Annual Inventory of Equipment"),
    ),
    "9.6": (
        ("9.6.1", "Janitorial and Security Contracts"),
        ("9.6.2", "Profile of Physical Plant and General Services"),
        ("9.6.3", "Building Maintenance Program/Evaluation of the Maintenance Program"),
        ("9.6.4", "Provision for Inter-Office and External Communications"),
        ("9.6.5", "Inventory of Provisions for Fire Safety"),
    ),
    "9.7": (
        ("9.7.1", "Pictures of Physical Plant and Facilities"),
    ),
    "9.8": (
        ("9.8.1", "Monthly Inspection Report"),
        ("9.8.2", "MOA with Garbage Collecting Agency"),
        ("9.8.3", "Waste Management Plan"),
        ("9.8.4", "Emergency Crisis Management Manual"),
    ),
    "10.1": (
        ("10.1.1", "SEC Registration and Articles of Incorporation"),
        ("10.1.2", "Profile of the Board of Trustees"),
        ("10.1.3", "Policy on Preparation and Conduct of the Monthly Board Meeting"),
        ("10.1.4", "Organizational Chart"),
        ("10.1.5", "Job Description of the President (JDM 4.01)"),
        ("10.1.6", "Job Description Manual"),
        ("10.1.7", "Operational Procedures Manual"),
        ("10.1.8", "Quality Management Manual"),
        ("10.1.9", "List of Institutional Committees/Councils"),
        ("10.1.10", "Minutes of Meetings (ManComm)"),
        ("10.1.11", "Initiatives of Development of Relations with External Stakeholders"),
    ),
    "10.2": (
        ("10.2.1", "Profile of Academic Council"),
        ("10.2.2", "Job Description of Academic Officers"),
        ("10.2.3", "Policy on Curriculum Review and Validation"),
        ("10.2.4", "Program Curriculum"),
        ("10.2.5", "Sample Syllabi"),
        ("10.2.6", "Policy on Selection and Development of Course Material"),
        ("10.2.7", "Policy on Student Assessment"),
        ("10.2.8", "Records Showing Participation of Academic Officers in Budget Preparation"),
        ("10.2.9", "Policy on Conduct of Institutional Research"),
        ("10.2.10", "Approved Research Budget/Provisions for Financial Assistance Given to Faculty Researchers"),
    ),
    "10.3": (
        ("10.3.1", "SSS Personnel Profile"),
        ("10.3.2", "Policy on Enrolment Process"),
        ("10.3.3", "Admission Center Functional Chart"),
        ("10.3.4", "Job Description of the Admission Director"),
        ("10.3.5", "Student Brochures"),
        ("10.3.6", "Picture of Enrolment Procedure Displayed near the Enrolment Area"),
        ("10.3.7", "Policy on Student Retention"),
        ("10.3.8", "Proof for Interviews and Pre-Counseling Sessions"),
        ("10.3.9", "Student Handbook"),
        ("10.3.10", "Schedule of Fees"),
        ("10.3.11", "Guidelines and Procedures on Assessment Refunds"),
        ("10.3.12", "Policy on Adding and Dropping"),
        ("10.3.13", "Class Schedules"),
        ("10.3.14", "Policy on Freshmen Orientation"),
        ("10.3.15", "Evaluation and Documentation of Orientation for New Students/Transferees"),
    ),
    "10.4": (
        ("10.4.1", "Functional Chart of Accounting and Finance Department"),
        ("10.4.2", "Personnel Profile of Accounting, Finance and Purchasing"),
        ("10.4.3", "Financial System"),
        ("10.4.4", "Variance Report per Unit"),
        ("10.4.5", "Audited Financial Statement, SY 2024-2025"),
        ("10.4.6", "Approved Institutional Budget, SY 2023-2024 & SY 2024-2025"),
        ("10.4.7", "Approved Salary Scale for Teaching and Non-teaching Personnel"),
        ("10.4.8", "Policy on Purchasing Process"),
        ("10.4.9", "Summary of Insurance Coverages"),
        ("10.4.10", "Policy on Physical Plant Maintenance"),
        ("10.4.11", "Policy on Ground Maintenance"),
        ("10.4.12", "Annual Operational Plan of Physical Plant Maintenance"),
        ("10.4.13", "Annual Operational Plan of New Projects"),
        ("10.4.14", "Repair Records"),
    ),
    "10.5": (
        ("10.5.1", "Sample Minutes of BOT"),
        ("10.5.2", "Sample Minutes of Faculty Meetings"),
        ("10.5.3", "Sample Minutes of Committee Meetings"),
        ("10.5.4", "Faculty Profile"),
        ("10.5.5", "Student Directory/Screenshots of Student General Information Sheet"),
        ("10.5.6", "Summary of Annual Enrolment"),
        ("10.5.7", "Summary of Enrolment by Class, Sex and Course"),
        ("10.5.8", "Sample Academic, Guidance and Health Records of Students"),
        ("10.5.9", "Sample Academic/Management Reports to BOT"),
        ("10.5.10", "Proof of Financial Assistance"),
        ("10.5.11", "Summary of Disciplinary Matters from OSA"),
        ("10.5.12", "Registrar's Policies on Security and Confidentiality of Student Records"),
        ("10.5.13", "Policy on Request for Student Credentials"),
        ("10.5.14", "Policy on Request for Correction of Grade"),
        ("10.5.15", "Policy on Completion of Grades"),
        ("10.5.16", "Policy on Authentication of Records"),
    ),
    "10.6": (
        ("10.6.1", "Profile of the Academic and Non-academic Councils/Committees"),
        ("10.6.2", "Policy on Offering of New Programs"),
    ),
    "10.7": (
        ("10.7.1", "Policy on Strategic and Operational Planning/Strategic Planning Framework"),
        ("10.7.2", "JMCFI Strategic Roadmap"),
        ("10.7.3", "JMCFI Institutional Monitoring Framework"),
        ("10.7.4", "Five-Year Strategic Plan"),
        ("10.7.5", "College Annual Operational Plan SY 2026-2027"),
        ("10.7.6", "College Accomplishment Report SY 2024-2025"),
    ),
    "10.8": (
        ("10.8.1", "Functional Chart of QAO"),
        ("10.8.2", "QMO Annual Operational Plan"),
        ("10.8.3", "Annual Operational Plan of the College"),
        ("10.8.4", "Progress/Accomplishment Reports"),
        ("10.8.5", "Institutional Strategic Plan SY 2022-2027"),
        ("10.8.6", "Accomplishment Report of ISP 2022-2027"),
        ("10.8.7", "Management Review"),
        ("10.8.8", "Academic Innovations for CQI"),
    ),
    "10.9": (
        ("10.9.1", "JMCFI HR Bulletin"),
        ("10.9.2", "President's Annual Report 2025"),
        ("10.9.3", "Assets Inventory"),
        ("10.9.4", "Proceedings/Minutes of the following"),
        ("10.9.5", "List of Academic Innovations for Continuous Quality Improvements"),
        ("10.9.6", "Evaluation of the Implemented CQIs"),
    ),
}
