# Generated by Django 6.0.7 on 2026-08-17 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccreditationCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('academic_year', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-is_active', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='EvidenceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_DEAN_REVIEW', 'Under Dean Review'), ('UNDER_AREA_CHAIR_REVIEW', 'Under Area Chair Review'), ('UNDER_QA_REVIEW', 'Under QA Review'), ('NEEDS_REVISION', 'Needs Revision'), ('COMPLIED', 'Complied'), ('NON_COMPLIED', 'Non-Complied'), ('CLOSED', 'Closed')], default='DRAFT', max_length=35)),
                ('self_evaluation', models.TextField(blank=True)),
                ('actual_situation', models.TextField(blank=True)),
                ('revision_return_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_DEAN_REVIEW', 'Under Dean Review'), ('UNDER_AREA_CHAIR_REVIEW', 'Under Area Chair Review'), ('UNDER_QA_REVIEW', 'Under QA Review'), ('NEEDS_REVISION', 'Needs Revision'), ('COMPLIED', 'Complied'), ('NON_COMPLIED', 'Non-Complied'), ('CLOSED', 'Closed')], max_length=35)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('requirement__code', 'department__name'),
            },
        ),
        migrations.CreateModel(
            name='EvidenceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('self_evaluation', models.TextField(blank=True)),
                ('actual_situation', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-version_number',),
            },
        ),
        migrations.CreateModel(
            name='AccreditationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('status_label', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='accreditation.accreditationcycle')),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='AccreditationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='accreditation.accreditationlevel')),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='AccreditationSubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=240)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subareas', to='accreditation.accreditationarea')),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='EvidenceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='evidence/%Y/%m/%d/')),
                ('link_url', models.URLField(blank=True)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EvidenceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('required_description', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_requirements', to='accreditation.accreditationarea')),
                ('subarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_requirements', to='accreditation.accreditationsubarea')),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='EvidenceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_DEAN_REVIEW', 'Under Dean Review'), ('UNDER_AREA_CHAIR_REVIEW', 'Under Area Chair Review'), ('UNDER_QA_REVIEW', 'Under QA Review'), ('NEEDS_REVISION', 'Needs Revision'), ('COMPLIED', 'Complied'), ('NON_COMPLIED', 'Non-Complied'), ('CLOSED', 'Closed')], max_length=35)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_DEAN_REVIEW', 'Under Dean Review'), ('UNDER_AREA_CHAIR_REVIEW', 'Under Area Chair Review'), ('UNDER_QA_REVIEW', 'Under QA Review'), ('NEEDS_REVISION', 'Needs Revision'), ('COMPLIED', 'Complied'), ('NON_COMPLIED', 'Non-Complied'), ('CLOSED', 'Closed')], max_length=35)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REQUEST_REVISION', 'Request Revision'), ('COMPLIED', 'Complied'), ('NON_COMPLIED', 'Non-Complied'), ('CLOSED', 'Closed')], max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
