# Generated by Django 6.0.7 on 2026-08-17 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accreditation', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencereview',
            name='reviewer_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_reviews', to='core.role'),
        ),
        migrations.AddField(
            model_name='evidencesubmission',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_evidence_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidencesubmission',
            name='current_review_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_evidence_reviews', to='core.role'),
        ),
        migrations.AddField(
            model_name='evidencesubmission',
            name='current_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_evidence_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidencesubmission',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_submissions', to='core.department'),
        ),
        migrations.AddField(
            model_name='evidencesubmission',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_evidence_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidencesubmission',
            name='program_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_evidence_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidencesubmission',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='accreditation.evidencerequirement'),
        ),
        migrations.AddField(
            model_name='evidencesubmission',
            name='revision_return_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_return_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidencesubmission',
            name='revision_return_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revision_return_submissions', to='core.role'),
        ),
        migrations.AddField(
            model_name='evidencereview',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accreditation.evidencesubmission'),
        ),
        migrations.AddField(
            model_name='evidencecomment',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accreditation.evidencesubmission'),
        ),
        migrations.AddField(
            model_name='evidenceversion',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='accreditation.evidencesubmission'),
        ),
        migrations.AddField(
            model_name='evidenceversion',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidencereview',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='accreditation.evidenceversion'),
        ),
        migrations.AddField(
            model_name='evidencefile',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='accreditation.evidenceversion'),
        ),
        migrations.AddField(
            model_name='evidencecomment',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='accreditation.evidenceversion'),
        ),
        migrations.AddConstraint(
            model_name='accreditationlevel',
            constraint=models.UniqueConstraint(fields=('cycle', 'code'), name='unique_cycle_level_code'),
        ),
        migrations.AddConstraint(
            model_name='accreditationarea',
            constraint=models.UniqueConstraint(fields=('level', 'code'), name='unique_level_area_code'),
        ),
        migrations.AddConstraint(
            model_name='accreditationarea',
            constraint=models.UniqueConstraint(fields=('level', 'slug'), name='unique_level_area_slug'),
        ),
        migrations.AddConstraint(
            model_name='accreditationsubarea',
            constraint=models.UniqueConstraint(fields=('area', 'code'), name='unique_area_subarea_code'),
        ),
        migrations.AddConstraint(
            model_name='evidencerequirement',
            constraint=models.UniqueConstraint(fields=('area', 'code'), name='unique_area_evidence_code'),
        ),
        migrations.AddConstraint(
            model_name='evidencesubmission',
            constraint=models.UniqueConstraint(fields=('requirement', 'department'), name='unique_requirement_department_submission'),
        ),
        migrations.AddConstraint(
            model_name='evidenceversion',
            constraint=models.UniqueConstraint(fields=('submission', 'version_number'), name='unique_submission_version'),
        ),
    ]
