# Generated by Django 6.0.7 on 2026-08-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencerequirement',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
