# Generated by Django 6.0.8 on 2026-09-02 03:32

from django.db import migrations, models


def backfill_version_flags(apps, schema_editor):
    EvidenceVersion = apps.get_model('accreditation', 'EvidenceVersion')
    for submission_id in EvidenceVersion.objects.values_list('submission_id', flat=True).distinct():
        versions = list(
            EvidenceVersion.objects.filter(submission_id=submission_id).order_by('-version_number')
        )
        if not versions:
            continue
        versions[0].is_current = True
        versions[0].status = 'SUBMITTED'
        for version in versions[1:]:
            version.is_current = False
            version.status = 'SUPERSEDED'
        EvidenceVersion.objects.bulk_update(versions, ['is_current', 'status'])


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0003_evidencerequirement_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenceversion',
            name='change_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evidenceversion',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evidenceversion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('NOT_APPROVED', 'Not Approved'), ('APPROVED', 'Approved'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=25),
        ),
        migrations.RunPython(backfill_version_flags, migrations.RunPython.noop),
    ]
