# Generated by Django 6.0.8 on 2026-09-02 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-last_read_at',),
            },
        ),
        migrations.AddField(
            model_name='message',
            name='client_message_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('client_message_id__gt', '')), fields=('conversation', 'client_message_id'), name='unique_conversation_client_message'),
        ),
        migrations.AddField(
            model_name='messageread',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='resources.conversation'),
        ),
        migrations.AddField(
            model_name='messageread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='messageread',
            constraint=models.UniqueConstraint(fields=('user', 'conversation'), name='unique_user_conversation_read'),
        ),
    ]
